name: Build Container Image

on:
  schedule:
    - cron: 0 2 * * 6
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker build
        id: build
        uses: docker/setup-build-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.build-cache
          key: ${{ runner.os }}-build-${{ hashFiles('cache_buster') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('cache_buster') }}-

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.build.outputs.name }}
          context: ./
          target: prod
          platforms: linux/amd64
          tags: ramblurr/authentik:stable
          cache-from: type=local,src=/tmp/.build-cache
          cache-to: type=local,dest=/tmp/.build-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.build-cache
          mv /tmp/.build-cache-new /tmp/.build-cache
